### ISSUE TITLE
[Feature Request] Multiple Stylesheets per website

### ISSUE THREAD

**Issue by kyroath** [ankit/stylebot#635] opened 2021-04-13 08:13 UTC
**Is your feature request related to a problem? Please describe.**
I use the css editing part to enable different themes, like dark/light for websites. Right now, I'm commenting out the parts of the style I don't want at the moment.

**Describe the solution you'd like**
Having multiple stylesheets that we can name and then toggle on and off would solve this issue completely.

**Comment by ankit** [comment] 2021-04-13 17:18
thanks @kyroath - closing this as a duplicate of #621

**Closed by ankit** 2021-04-13 17:18 UTC
