### ISSUE TITLE
[Bug] Comment highlight shouldn't happen under some circumstances.

### ISSUE THREAD

**Issue by TsukiZero** [ankit/stylebot#774] opened 2024-03-06 14:46 UTC
Let's take a look at this:
![image](https://github.com/ankit/stylebot/assets/78157224/333e8eb4-d5c8-4304-9af0-2c4b72c7ad35)
According to this, anything in the line after the double slash there would be treated as a comment, right? But in reality, that does not happen and this rule works as it should!

**Comment by ankit** [comment] 2024-05-15 23:01
Closing this is as a duplicate of #763

**Closed by ankit** 2024-05-15 23:01 UTC
