### ISSUE TITLE
Stylebot reorders my rules on browser restart and wreaks havoc on my page

### ISSUE THREAD

**Issue by viridium** [ankit/stylebot#439] opened 2016-08-09 16:27 UTC
Upon browser restart, this saved CSS:

```
@import url(https://fonts.googleapis.com/css?family=Droid+Sans:400,700);
@import url(https://fonts.googleapis.com/css?family=Droid+Sans+Mono:400,700);

:not(.CodeMirror) { font-family: 'Droid Sans'; }
.CodeMirror * { font-family: 'Droid Sans Mono'; }
```

Gets reordered to this:

```
.CodeMirror * { font-family: 'Droid Sans Mono'; }
:not(.CodeMirror) { font-family: 'Droid Sans'; }

@import url(https://fonts.googleapis.com/css?family=Droid+Sans:400,700);
@import url(https://fonts.googleapis.com/css?family=Droid+Sans+Mono:400,700);
```

Needless to say, my page then looks very different.

**Comment by ackmanx** [comment] 2020-07-01 15:03
Resurrecting because this is still an issue. Hopefully with the extension getting new attention this can get fixed

**Comment by ankit** [comment] 2020-07-25 03:32
closing as duplicate of #452. will be fixed in upcoming release

**Closed by ankit** 2020-07-25 03:32 UTC
