### ISSUE TITLE
z-index issue are there in add style menu

### ISSUE THREAD

**Issue by gurrrung** [ankit/stylebot#675] opened 2021-11-10 16:47 UTC
### Describe the bug
When I click on `Add a new style...` button and menu looks like given below:

### Browser
Latest chrome stable

### To Reproduce
- Open Stylebot Menu.
- Click on `Add a new style...` button.

### Expected behavior
z-index issues should not be there

### Screenshots
![Screenshot from 2021-11-10 22-15-12](https://user-images.githubusercontent.com/30543444/141156031-7d94d13a-dec6-4c97-8443-6e529bbf423d.png)

**Comment by ankit** [comment] 2021-12-14 22:02
closing as duplicate of #654

**Closed by ankit** 2021-12-14 22:02 UTC
