### ISSUE TITLE
[Bug] Enabling stylebot makes me unable to load google docs

### ISSUE THREAD

**Issue by paprikati** [ankit/stylebot#574] opened 2020-08-06 18:58 UTC
**Describe the bug**
If I enable this extension (on chrome), I cannot load any documents stored in GSuite. I get an error:
![image](https://user-images.githubusercontent.com/50166767/89571167-25eb8800-d81f-11ea-985f-ce02e275749f.png)

**To Reproduce**
Enable the extension
Go to drive.google.com
Try to load a google doc

**Expected behavior**
Google docs should be able to load despite the plugin

**Additional context**
This was fine until last week, when it suddenly started breaking.

**Comment by ankit** [comment] 2020-08-06 20:17
@paprikati thanks for reporting. I am not able to reproduce this but this _may_ be fixed in the latest release since I have made fixes to reduce the amount of conflict stylebot has with the underlying page. Once the release is approved by the web store, I will let you know so you can help me test.

Thanks!

**Closed** 2021-04-17 05:08 UTC
Labels: bug, not able to reproduce
