### ISSUE TITLE
auto sync

### ISSUE THREAD

**Issue by ahadto** [ankit/stylebot#443] opened 2016-08-22 14:22 UTC
i think this plugin need a feature to sync all styles with other browser in chrome (all browsers logged in with google account) and other browsers
thank you

**Comment by dwcouch** [comment] 2016-09-14 13:41
Yes I agree. I had wrongly assumed that Chrome would sync the settings if I were logged. Please enable support for this.

**Comment by ankit** [comment] 2020-07-25 03:23
closing as duplicate of #230

**Closed by ankit** 2020-07-25 03:23 UTC
