### ISSUE TITLE
not support @import

### ISSUE THREAD

**Issue by greathan** [ankit/stylebot#483] opened 2017-08-15 09:07 UTC
@import url('https://fonts.googleapis.com/css?family=Saira'); 
not work

**Comment by RX-3200** [comment] 2017-09-08 16:56
you must use something like tis
`@import url("http://usercss.ru/styles/night/night.css");`
it's work

**Comment by ankit** [comment] 2020-07-25 03:19
closing as duplicate of #501

**Closed by ankit** 2020-07-25 03:19 UTC
