### ISSUE TITLE
auto backup

### ISSUE THREAD

**Issue by solom2u2** [ankit/stylebot#489] opened 2017-11-02 19:12 UTC
Is there a way to auto backup styles? I sometime forget to export them and go ahead and delete my Chrome userdata folder, then I remember when it was too late. I hope there is something like emailing the styles every week or so.. or anything to that effect..

**Comment by tobia** [comment] 2018-03-17 14:40
This would be most useful.

**Comment by ilemhadri** [comment] 2018-09-30 19:49
Agreed! A much wanted feature.

**Comment by ankit** [comment] 2020-07-11 19:21
closing as duplicate of #230

**Closed by ankit** 2020-07-11 19:21 UTC
Labels: Feature, v3
