### ISSUE TITLE
Stylebot div is being added to text editor

### ISSUE THREAD

**Issue by viroxd** [ankit/stylebot#560] opened 2020-07-29 19:55 UTC
I've seen this twice today now.  Once in Joomla, and again in Wordpress.
![image](https://user-images.githubusercontent.com/15499927/88846269-40c45980-d19a-11ea-8ea0-87f5aa63f97b.png)

I didn't notice this before, and the only changes I made recently were to the global css:

.wp-block {
  max-width: unset;
}

body.wp-admin .fusion_code .CodeMirror {
  height: 600px;
  left: -200px;
  resize: both;
  width: calc(100% + 200px);
}

**Comment by ankit** [comment] 2020-07-29 20:43
@viroxd thanks for reporting, closing as a duplicate of #561. It would be very useful if you can give me a publicly accessible URL on #561 where i can test and fix this on

**Closed by ankit** 2020-07-29 20:43 UTC
