### ISSUE TITLE
Toggle !important?

### ISSUE THREAD

**Issue by speeditor** [ankit/stylebot#437] opened 2016-07-29 00:25 UTC
Giving the option of a button previewing or fully toggling `!important` helps people check whether CSS they are drafting using Stylebot works without the !important suffix.

**Comment by tdechangy** [comment] 2018-11-09 20:44
Could you please consider this option. This would make your plugin a definite Designer's killer tool !!! It will allow to gain so much time remove the efforts to go back and forth just to see how to adjust the code.

Looking forward for your clever upgrades.
Best.

**Comment by No5972** [comment] 2019-01-04 17:05
+2

**Comment by ankit** [comment] 2020-07-25 03:26
closing as duplicate of #170

**Closed by ankit** 2020-07-25 03:26 UTC
