### ISSUE TITLE
Support @import

### ISSUE THREAD

**Issue by Supuhstar** [ankit/stylebot#407] opened 2015-10-02 16:02 UTC
`@import` statements don't apply:

![Illustrative screenshot](http://i.imgur.com/N1BpOgs.png)

The above screenshot shows Stylebot, in live mode, with an `@import` statement and a generic rule that only selects the non-existent "bad-rule" element and applies no styles. The inspector shows that the "bad-rule" rule is included, but not the `@import` statement.

**Comment by ankit** [comment] 2020-07-25 03:37
closing as duplicate of #501

**Closed by ankit** 2020-07-25 03:37 UTC
