### ISSUE TITLE
Save styles across computers

### ISSUE THREAD

**Issue by viridium** [ankit/stylebot#440] opened 2016-08-09 16:29 UTC
It's unpleasant to have to copy/paste my styles between machines. Can Stylebot automatically put my styles in the cloud and distribute them to all my machines? Happy to log in with Google OpenID to help it know who I am.

**Comment by karol-depka** [comment] 2019-04-16 01:35
Hi. I would like to implement this. Will this be accepted as Pull Request?

**Comment by ankit** [comment] 2020-07-30 03:16
closing as duplicate of #230

**Closed by ankit** 2020-07-30 03:16 UTC
Labels: Duplicate
