### ISSUE TITLE
[Bug] Stylebot 3.0 causes issues when going to another chapter while signed in on RoyalRoad.com

### ISSUE THREAD

**Issue by dragonkin550** [ankit/stylebot#564] opened 2020-07-30 09:01 UTC
**Describe the bug**
Occurs due to Stylebot when signed in on RoyalRoad.com - when going to the next or previous chapter of a story, a popup comes up stating "You have a pending comment in the editor.  Are you sure you want to leave the page without sending it?"  

This occurs despite never having written anything in the comment box, and it appears to happen because stylebot adds the following html to the comment iframe: "\<div id="stylebot" style="top: 0; height: 100%; position: fixed; z-index: 100000000; line-height: 20px"\>...." which adds a bunch of css seemingly for the readability option.

**To Reproduce**
- Go to Royalroad.com
- Sign in with an account to enable commenting
- Click on any story chapter, such as "https://www.royalroad.com/fiction/7509/world-keeper/chapter/530499/chapter-538-growing-darkness"
- Wait for the page to completely finish loading the comment section
- Hit the 'next chapter' or 'previous chapter' buttons (or hit the left / right arrow key for the same effect)
- get the popup 

**Expected behavior**
Expected behavior is that clicking the next chapter / previous chapter buttons directly loads the next chapter or previous chapter without having to click away a popup.  

**Screenshots**
![Screenshot 2020-07-30 at 10 33 47 AM](https://user-images.githubusercontent.com/68990749/88902664-cf94ad00-d252-11ea-8576-f3c50b9b662b.png)
![Screenshot 2020-07-30 at 10 56 37 AM](https://user-images.githubusercontent.com/68990749/88903085-63667900-d253-11ea-8ec1-cb3b25fe4340.png)

**Additional context**
Selecting the stylebot \<div\> element and deleting it removes the problem.  Ideal fix would be a way of simply disabling this behavior - I don't see myself using the readability option all that often, so if this css is required for the readability option, then a way to disable its functionality would be nice.

**Comment by ankit** [comment] 2020-07-30 15:43
Thanks for the detailed bug report @dragonkin550. Closing this as a duplicate of #561. The fix is currently in review in the Chrome Web Store.

**Closed by ankit** 2020-07-30 15:43 UTC
Labels: Bug, Duplicate
