### ISSUE TITLE
[Feature Request] Are there any plans to support WebDAV for sync/backup?

### ISSUE THREAD

**Issue by cantwork** [ankit/stylebot#591] opened 2020-09-23 08:28 UTC
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
i hope the sync/backup not just include dropbox/google drive..

**Additional context**
can`t find other style manager which could support WebDAV..
if someone have idea, call me plz.

**Comment by ankit** [comment] 2020-11-09 04:43
@cantwork Most likely, it will be hard to support WebDAV in the beginning. Initially, I might try to support any of the popular sync services. However, I will keep your request in mind in case it is easy to support. Thanks for the request. Closing this as duplicate of #230

**Closed by ankit** 2020-11-09 04:43 UTC
